
version: '{branch}-{build}'
image: Visual Studio 2026

branches:
  only:
    - master

configuration: Release

before_build:
  nuget restore

build:
  parallel: true
  project: Pbkdf2.slnx
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  
deploy:
  provider: NuGet
  api_key:
    secure: 1FFrOQ1to7x108dE3YPb8ACDEx7kJOJUXBw1M3RE5b8JeMa/G5qYffI1ZJg3td7o
  skip_symbols: false
  