
version: '{branch}-{build}'
image: Visual Studio 2022

branches:
  only:
    - master

configuration: Release
platform: Any CPU

build:
  parallel: true
  project: Pbkdf2.sln
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
  
deploy:
  provider: NuGet
  api_key:
    secure: QsAfyY+46GeTCjC+L2kjV6/1AriR3nxjHm8EUru4epPuwl9IHaqAlC13H5TCWyBF
  skip_symbols: false
  