
version: '{branch}-{build}'
image: Visual Studio 2022

branches:
  only:
    - master

configuration: Release

before_build:
  nuget restore

build:
  parallel: true
  project: Pbkdf2.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  
deploy:
  provider: NuGet
  api_key:
    secure: FXdfurOFdTV/iNGNBf9Vqb3teeqGMrwuMxpoWQMVzHsZ9roqoCCGOQxrzhRM5Wwm
  skip_symbols: false
  